<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class report extends Model
{
    use HasFactory;
    protected $fillable = [
        'id',
        'report_id',
        'repoort_brgy',
        'narrative',
        'reportType',
        'date',
        'time',
        'media',
        'location',
        'barangay',
        'reportstatus',
        'irf_entry',
        'blotter_entry',
        'copy_for',
        'administering_officer',
        'administering_officer_phone',
        'deskofficer_name',
        'deskofficer_phone',
        'investigator_on_case',
        'investigator_on_case_phone',
        'chief_of_head',
        'chief_of_head_phone',
        'report_archive_status',
        'susfname',
        'susmname',
        'suslname',
        'susqualifier',
        'susnickname',
        'suscitizenship',
        'sussex',
        'suscivilstatus',
        'susbirth',
        'susage',
        'susplaceofbirth',
        'sushomephone',
        'susmobilephone',
        'susstreet',
        'susbarangay',
        'susmunicipality',
        'susprovince',
        'susstreet2',
        'susbarangay2',
        'susmunicipality2',
        'susprovince2',
        'sushighesteduc',
        'susoccupation',
        'suswordaddress',
        'susrelationtovictim',
        'susemail',
        'susifrank',
        'susunitassignment',
        'susgroup',
        'suscrimerecord',
        'susspecifyrecord',
        'susstatusrecord',
        'susheight',
        'susweight',
        'susbuild',
        'suscoloreyes',
        'susdescripeyes',
        'susdescriphair',
        'susinfluence',
        'chilguardian',
        'chilguardianaddress',
        'chilhomephone',
        'chilmobilephone',
        
        'vicfname',
        'vicmname',
        'viclnam',
        'vicqualifier',
        'vicnickname',
        'viccitizenship',
        'vicsex',
        'viccivilstat',
        'vicbirth',
        'vicage',
        'vicplaceofbirth',
        'vichomephone',
        'vicmobilephone',
        'vicstreet',
        'vicbarangay',
        'vicmunicipality',
        'vicprovince',
        'vicstreet2',
        'vicbarangay2',
        'vicmunicipality2',
        'vicprovince2'
,


    ];

    const UPDATED_AT = null;
}
